
dist: trusty
sudo: false
language: node_js
cache: npm
node_js:
  - '8'

script: echo "Running tests against $(node -v) ..."

install:
  - npm install 

addons:
  chrome: stable


stages:
  - name: "Build"
  - name: "Lint"
  - name: "Test"
  - name: "Publish"
    if: branch = master AND type = push
  - name: "Stackblitz"

jobs:
  include:
    - stage: "Build"    
      script:
        - echo "Running Build against $(node -v) ..."
        - npm run build

    - stage: "Lint"  
      script:
        - echo "Running Lint against $(node -v) ..."
        - npm run lint
    
    - stage: "Test"  
      script:
        - echo "Running Test against $(node -v) ..."
        - npm run test
        - codecov

    - stage: "Stackblitz"

    - stage: "Publish"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          
          - ls
          - npm run semantic-release:run
        on:
          branch: master



# after_success:
# - bash <(curl -s https://codecov.io/bash)