
dist: trusty
sudo: false
language: node_js
node_js:
  - '8'

cache:
  directories:
    - ./node_modules


script: echo "Running tests against $(node -v) ..."

install:
  - npm install 

# stages:
#   - name: "Build"
    

#   - name: "Lint"
#   - name: "Test"
#   - name: "Publish"
#   - name: "Stackblitz"

# jobs:
#   include:
#     - stage: "Build"
      
#       script:
#         - echo "Running Build against $(node -v) ..."

#     - stage: "Lint"  
#       script:
#         - echo "Running Lint against $(node -v) ..."
    
#     - stage: "Test"  
#       script:
#         - echo "Running Test against $(node -v) ..."

#     - stage: "Stackblitz"

deploy:
    provider: script
    skip_cleanup: true
    script:
      # if: branch = master AND type = push
      - nvm install lts/*
      - npm run semantic-release
# after_success:
# - bash <(curl -s https://codecov.io/bash)